CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    width DOUBLE PRECISION,
    length DOUBLE PRECISION,
    height DOUBLE PRECISION,
    shape VARCHAR(64),
    wall_color VARCHAR(32),
    floor_type VARCHAR(64),
    floor_color VARCHAR(32),
    ceiling_color VARCHAR(32)
);
