spring.config.import=optional:file:src/.env.properties

spring.application.name=backend

server.port=${SERVER_PORT}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

app.db.url=${DB_URL}
app.db.username=${DB_USERNAME}
app.db.password=${DB_PASSWORD}
