import type { User } from '@/types/auth.types';
import type { Design } from '@/types/design.types';
import type { FurnitureItem } from '@/types/furniture.types';
import type { Room } from '@/types/room.types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Sarah Mitchell',
  email: 'sarah@furnishvista.com',
  avatar: undefined,
  role: 'designer',
  createdAt: '2025-09-15T10:00:00Z',
};

export const mockFurniture: FurnitureItem[] = [
  {
    id: 'fur-1',
    name: 'Small Sofa',
    category: 'seating',
    modelPath: '/models/Couch Small.glb',
    thumbnail: '/images/chair-thumb.png',
    defaultWidth: 0.6,
    defaultLength: 0.5,
    defaultHeight: 0.6,
    color: '#8B7355',
    description: 'Compact two-seater sofa',
  },
  {
    id: 'fur-2',
    name: 'Desk',
    category: 'tables',
    modelPath: '/models/Desk.glb',
    thumbnail: '/images/desk-thumb.png',
    defaultWidth: 0.6,
    defaultLength: 0.6,
    defaultHeight: 0.7,
    color: '#654321',
    description: 'Wooden work desk',
  },
  {
    id: 'fur-3',
    name: 'Night Stand',
    category: 'tables',
    modelPath: '/models/Night Stand.glb',
    thumbnail: '/images/drawer-thumb.png',
    defaultWidth: 0.5,
    defaultLength: 0.4,
    defaultHeight: 0.55,
    color: '#D4A574',
    description: 'Bedside night stand with drawer',
  },
  {
    id: 'fur-4',
    name: 'Wide Sofa',
    category: 'seating',
    modelPath: '/models/Couch Wide.glb',
    thumbnail: '/images/sofa-thumb.png',
    defaultWidth: 1,
    defaultLength: 0.9,
    defaultHeight: 0.6,
    color: '#4A6741',
    description: 'Large three-seater sofa',
  },
  {
    id: 'fur-5',
    name: 'Wardrobe',
    category: 'storage',
    modelPath: '/models/Closet.glb',
    thumbnail: '/images/closet-thumb.png',
    defaultWidth: 1,
    defaultLength: 0.9,
    defaultHeight: 2.0,
    color: '#8B6914',
    description: 'Full-height wardrobe closet',
  },
  {
    id: 'fur-6',
    name: 'Floor Lamp',
    category: 'lighting',
    modelPath: '/models/Lamp Round Floor.glb',
    thumbnail: '/images/lamp-thumb.png',
    defaultWidth: 0.4,
    defaultLength: 0.4,
    defaultHeight: 1.6,
    color: '#2C2C2C',
    description: 'Modern round floor lamp',
  },
  {
    id: 'fur-7',
    name: 'Table',
    category: 'tables',
    modelPath: '/models/Table.glb',
    thumbnail: '/images/table-thumb.png',
    defaultWidth: 1,
    defaultLength: 0.75,
    defaultHeight: 0.75,
    color: '#A0522D',
    description: 'Rectangular dining table',
  },
  {
    id: 'fur-8',
    name: 'Double Bed',
    category: 'seating',
    modelPath: '/models/Bed Double.glb',
    thumbnail: '/images/bed-thumb.png',
    defaultWidth: 1,
    defaultLength: 1.5,
    defaultHeight: 0.4,
    color: '#8B7355',
    description: 'Full-size double bed with headboard',
  },
];

const defaultRoom: Room = {
  id: 'room-1',
  name: 'Living Room',
  width: 5,
  length: 4,
  height: 3,
  shape: 'rectangular',
  wallColor: '#f5f5f4',
  floorType: 'wood',
  floorColor: '#d4a574',
  ceilingColor: '#ffffff',
};

export const mockDesigns: Design[] = [
  {
    id: 'design-1',
    name: 'Modern Living Room',
    room: { ...defaultRoom },
    furniture: [
      {
        id: 'placed-1',
        furnitureId: 'fur-4',
        position: { x: 2, y: 0, z: 1.5 },
        rotation: 0,
        scale: 1,
        color: '#4A6741',
        shading: 0.5,
      },
      {
        id: 'placed-2',
        furnitureId: 'fur-7',
        position: { x: 2, y: 0, z: 2.5 },
        rotation: 0,
        scale: 1,
        color: '#A0522D',
        shading: 0.5,
      },
      {
        id: 'placed-3',
        furnitureId: 'fur-6',
        position: { x: 0.5, y: 0, z: 0.5 },
        rotation: 0,
        scale: 1,
        color: '#2C2C2C',
        shading: 0.5,
      },
    ],
    createdAt: '2025-12-01T10:00:00Z',
    updatedAt: '2025-12-15T14:30:00Z',
    designerId: 'user-1',
  },
  {
    id: 'design-2',
    name: 'Cozy Dining Space',
    room: {
      id: 'room-2',
      name: 'Dining Room',
      width: 4,
      length: 3.5,
      height: 3,
      shape: 'rectangular',
      wallColor: '#E8E0D5',
      floorType: 'tile',
      floorColor: '#C4B5A3',
      ceilingColor: '#FFFFFF',
    },
    furniture: [
      {
        id: 'placed-4',
        furnitureId: 'fur-2',
        position: { x: 2, y: 0, z: 1.75 },
        rotation: 0,
        scale: 1,
        color: '#654321',
        shading: 0.5,
      },
      {
        id: 'placed-5',
        furnitureId: 'fur-8',
        position: { x: 1.2, y: 0, z: 1.75 },
        rotation: 90,
        scale: 1,
        color: '#696969',
        shading: 0.5,
      },
      {
        id: 'placed-6',
        furnitureId: 'fur-8',
        position: { x: 2.8, y: 0, z: 1.75 },
        rotation: 270,
        scale: 1,
        color: '#696969',
        shading: 0.5,
      },
    ],
    createdAt: '2025-11-20T08:00:00Z',
    updatedAt: '2025-12-10T16:00:00Z',
    designerId: 'user-1',
  },
  {
    id: 'design-3',
    name: 'Reading Corner',
    room: {
      id: 'room-3',
      name: 'Study',
      width: 3,
      length: 3,
      height: 2.8,
      shape: 'rectangular',
      wallColor: '#F0EDE8',
      floorType: 'carpet',
      floorColor: '#8B8178',
      ceilingColor: '#FFFFFF',
    },
    furniture: [
      {
        id: 'placed-7',
        furnitureId: 'fur-1',
        position: { x: 0.8, y: 0, z: 0.8 },
        rotation: 45,
        scale: 1,
        color: '#8B7355',
        shading: 0.5,
      },
      {
        id: 'placed-8',
        furnitureId: 'fur-5',
        position: { x: 2.5, y: 0, z: 0.3 },
        rotation: 0,
        scale: 1,
        color: '#8B6914',
        shading: 0.5,
      },
      {
        id: 'placed-9',
        furnitureId: 'fur-6',
        position: { x: 0.3, y: 0, z: 0.3 },
        rotation: 0,
        scale: 1,
        color: '#2C2C2C',
        shading: 0.5,
      },
    ],
    createdAt: '2025-10-05T12:00:00Z',
    updatedAt: '2025-11-28T09:15:00Z',
    designerId: 'user-1',
  },
];
